# Generated by Django 4.1.7 on 2023-04-10 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('top_rank', models.IntegerField()),
                ('copy_sales', models.IntegerField()),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contry_of_origin', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('birth_day', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RecordCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('founded_date', models.DateField()),
                ('headquarters_location', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('genres', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('bpm', models.IntegerField()),
                ('released', models.IntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.album')),
            ],
        ),
        migrations.CreateModel(
            name='TrackArtistColab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaboration_type', models.CharField(max_length=255)),
                ('royalty_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='music.artist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='music.track')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='record_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='music.recordcompany'),
        ),
    ]
