# Generated by Django 4.2.1 on 2023-05-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='copy_sales',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='recordcompany',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='track',
            name='genres',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
