# Generated by Django 4.2.1 on 2023-05-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_album_copy_sales_alter_album_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='contry_of_origin',
        ),
        migrations.AddField(
            model_name='artist',
            name='country_of_origin',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
