# Generated by Django 4.2.1 on 2023-05-13 08:16

from django.db import migrations, models
from django.db import connection






class Migration(migrations.Migration):

    def update_counts(apps, schema_editor):
        with connection.cursor() as cursor:
            # Update tracks count for each album
            cursor.execute("""
                UPDATE music_album
                SET tracks_count = (
                    SELECT COUNT(*)
                    FROM music_track
                    WHERE music_track.album_id = music_album.id
                )
            """)

            # Update collaborations count for each artist
            cursor.execute("""
                UPDATE music_artist
                SET collaborations_count = (
                    SELECT COUNT(*)
                    FROM music_trackartistcolab
                    WHERE music_trackartistcolab.artist_id = music_artist.id
                )
            """)

            # Update albums count for each record company
            cursor.execute("""
                UPDATE music_recordcompany
                SET albums_count = (
                    SELECT COUNT(*)
                    FROM music_album
                    WHERE music_album.record_company_id = music_recordcompany.id
                )
            """)

            # Update collaborations count for each track
            cursor.execute("""
                UPDATE music_track
                SET collaborations_count = (
                    SELECT COUNT(*)
                    FROM music_trackartistcolab
                    WHERE music_trackartistcolab.track_id = music_track.id
                )
            """)



    dependencies = [
        ('music', '0003_remove_artist_contry_of_origin_and_more'),
    ]


    operations = [
        migrations.AddField(
            model_name='album',
            name='tracks_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='collaborations_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recordcompany',
            name='albums_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='collaborations_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(update_counts),

    ]
