# Generated by Django 4.2.1 on 2023-05-18 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_alter_confirmationcode_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='tracks_count',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='collaborations_count',
        ),
        migrations.RemoveField(
            model_name='recordcompany',
            name='albums_count',
        ),
        migrations.RemoveField(
            model_name='track',
            name='collaborations_count',
        ),
    ]
