version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./sql_scripts:/sql_scripts
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    volumes:
      - .:/app
    command: >
      bash -c "set -e &&
            #  python manage.py non_interactive_makemigrations &&
            #  python manage.py migrate 
            #  python manage.py populate_db &&
            #  python manage.py collectstatic --no-input &&
            #  gunicorn -b 0.0.0.0:8000 music_library.wsgi &&
            #  python manage.py runserver 0.0.0.0:8000
            #  gunicorn -b 0.0.0.0:8000 music_library.wsgi
               python manage.py runserver 0.0.0.0:8000"
            
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_INTERACTIVE=no