FROM python:3.9

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

# Add the shell script to the container
COPY copy_sql_scripts_if_exists.sh .

# Give execute permission to the script
RUN chmod +x copy_sql_scripts_if_exists.sh

# Run the script to copy sql_scripts if it exists
RUN ./copy_sql_scripts_if_exists.sh

CMD ["gunicorn", "-b", "0.0.0.0:8000", "music_library.wsgi"]
