FROM python:3.9

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt


COPY . .

COPY sql_scripts/ /app/sql_scripts/


CMD ["gunicorn", "-b", "0.0.0.0:8000", "music_library.wsgi"]
