version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./sql_scripts:/sql_scripts
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    volumes:
      - .:/app
    command: >
      bash -c "set -e &&
              python manage.py non_interactive_makemigrations &&
              python manage.py migrate &&
            # python manage.py populate_db &&
              gunicorn -b 0.0.0.0:8000 music_library.wsgi"
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_INTERACTIVE=no

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/letsencrypt
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certs:/etc/letsencrypt
    command: 
      - certonly 
      - --webroot 
      - --webroot-path=/etc/letsencrypt 
      - --email
      - necunos.6@gmail.com
      - --agree-tos 
      - --no-eff-email 
      - --staging 
      - --force-renewal 
      - -d
      - www.api.dobo-net.click
    depends_on:
      - nginx