version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./sql_scripts:/sql_scripts
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
  redis:
    image: redis:5.0.5
    ports:
      - "6379:6379"
  server:
    image: python:3.9
    volumes:
      - .:/app
    command: >
      bash -c "set -e &&
            daphne -b 0.0.0.0 -p 8000 music_library.asgi:application"
            
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_INTERACTIVE=no
  nginx:
    container_name: nginx
    image: nginx:1.25.0
    environment:
      - DOMAIN
    depends_on:
      - server
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./etc/nginx/templates:/etc/nginx/templates:ro
      - ./etc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot/data:/var/www/certbot
  certbot:
    container_name: certbot
    image: certbot/certbot:v2.6.0
    depends_on:
      - nginx
    command: >-
            certonly --reinstall --webroot --webroot-path=/var/www/certbot
            --email ${EMAIL} --agree-tos --no-eff-email
            -d ${DOMAIN}
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot
    entrypoint: "/bin/sh -c 'echo \"0 0 1 */2 * root python -c 'import random; import time; time.sleep(random.random() * 3600)' && certbot renew -q\" >> /etc/crontab && crond -f'"
